package:
  name: ac-diamond
  version: "1.0"

source:
  fn: AC-DIAMOND-1.0.tar.gz
  url: https://github.com/Maihj/AC-DIAMOND/archive/v1.0.tar.gz
  sha256: 68d94888449bf0c7f60af02073ea2329adc6b47f843f1f862f20fcfcc3121967

build:
  number: 1
  skip: True # [osx]
  string: boost{{CONDA_BOOST}}_0
  
requirements:
  build:
    - gcc # [linux]
    - boost >=1.53.0,{{CONDA_BOOST}}*
  run:
    - libgcc # [linux]
    - boost {{CONDA_BOOST}}*

test:
  commands:
    - ac-diamond --help

about:
  home: https://github.com/Maihj/AC-DIAMOND
  license: GNU Affero General Public License v3.0
  summary: AC-DIAMOND is a DNA-protein alignment tool