package:
  name: ac-diamond
  version: "1.0"

source:
  fn: AC-DIAMOND-1.0.tar.gz
  url: https://github.com/Maihj/AC-DIAMOND/archive/v1.0.tar.gz
  sha256: 07a680e2d4e4aaf5f5dd536b691a32b9e781ce5b2a7ef6780384e6749c97ea5d

build:
  number: 1

requirements:
  build:
    - gcc # [linux]
    - llvm # [osx]
  run:
    - libgcc # [linux]

test:
  commands:
    - ac-diamond --help

about:
  home: https://github.com/Maihj/AC-DIAMOND
  license: GNU Affero General Public License v3.0
  summary: 'AC-DIAMOND is a DNA-protein alignment tool'